export const SocketInMsg = {
    // STUDENT
    ANSWER: "SERVER/ANSWER",
    SIGNAL_STATE: "SERVER/SIGNAL_STATE",

    // TEACHER
    START_QUIZ: "SERVER/LAUNCH_QUIZ",
    STOP_QUIZ: "SERVER/FINISH_QUIZ"
}

export const SocketOutMsg = {
    // STUDENT
    STUDENT_CLASS_JOINED: "STUDENT/CLASS/CLASS_JOINED",
    STATE_UPDATE: "STUDENT/CLASS/STATE_UPDATE",
    START_QUIZ: "ALL/CLASS/START_QUIZ",
    STOP_QUIZ: "ALL/CLASS/STOP_QUIZ",

    // TEACHER
    TEACHER_CLASS_JOINED: "TEACHER/CLASS/CLASS_JOINED",

    ANSWER: "TEACHER/CLASS/ANSWER",
    SIGNAL_STATE: "TEACHER/CLASS/SIGNAL_STATE",
}

export const QuizInstanceState = {
    OFF: 'OFF',
    HEADING: 'HEADING',
    FEEDBACK: 'FEEDBACK'
}