export const RedisMsg = {
    ANSWER: "ANSWER",
    SIGNAL_STATE: "SIGNAL_STATE",
    START_QUIZ: "LAUNCH_QUIZ",
    STOP_QUIZ: "FINISH_QUIZ"
}

export const SocketOutMsg = {
    // TEACHER
    ANSWER: "TEACHER/CLASS/ANSWER",
    SIGNAL_STATE: "TEACHER/CLASS/SIGNAL_STATE",

    // STUDENT
    STATE_UPDATE: "STUDENT/CLASS/STATE_UPDATE",
    START_QUIZ: "STUDENT/CLASS/START_QUIZ",
    STOP_QUIZ: "STUDENT/CLASS/STOP_QUIZ"
}