export const APIActionTypes = {
    OPEN_ROOM: "REMOTE/OPEN_ROOM",
    OPEN_ROOM_SUCCESS: "REMOTE/OPEN_ROOM_SUCCESS",
    OPEN_ROOM_FAILURE: "REMOTE/OPEN_ROOM_FAILURE",

    CLOSE_ROOM: "REMOTE/CLOSE_ROOM",
    CLOSE_ROOM_SUCCESS: "REMOTE/CLOSE_ROOM_SUCCESS",
    CLOSE_ROOM_FAILURE: "REMOTE/CLOSE_ROOM_FAILURE",

    START_QUIZ: "CLASS/START_QUIZ",
    START_QUIZ_SUCCESS: "CLASS/START_QUIZ_SUCESS",
    START_QUIZ_FAILURE: "CLASS/START_QUIZ_FAILURE",

    END_QUIZ: "CLASS/END_QUIZ",
    END_QUIZ_SUCCESS: "CLASS/END_QUIZ_SUCCESS",
    END_QUIZ_FAILURE: "CLASS/END_QUIZ_FAILURE"
}

export const WSInActionTypes = {
    CLASS_JOINED: "TEACHER/CLASS/CLASS_JOINED",

    START_QUIZ: "ALL/CLASS/START_QUIZ",
    ANSWER: "TEACHER/CLASS/ANSWER",
    SIGNAL_STATE: "TEACHER/CLASS/SIGNAL_STATE"
}

export const WSOutActionTypes = {
    START_QUIZ: "SERVER/LAUNCH_QUIZ",
    STOP_QUIZ: "SERVER/FINISH_QUIZ",
    SHOW_FEEDBACK: "SERVER/CLASS/SHOW_FEEDBACK"
}