export const ActionTypes = {
    CHOOSE: "QUESTIONNAIRE/CHOOSE",
    VALIDATE: "QUESTIONNAIRE/VALIDATE",

    // to move between quiz
    NEXT_CONSUL_QUIZ: "QUESTIONNAIRE/NEXT_QUIZ",
    PREV_CONSUL_QUIZ: "QUESTIONNAIRE/PREVIOUS_QUIZ",

    SEE_CORRECTION: "QUESTIONNAIRE/SEE_CORRECTION",

    CHOOSE_QUIZ: "QUESTIONNAIRE/CHOOSE_QUIZ",
    // CHOOSE_COMBOQUIZ: "QUESTIONNAIRE/CHOOSE_COMBOQUIZ",

    RETURN_TO_CHOICES : "QUESTIONNAIRE/RETURN_TO_CHOICES"
}